import React, { createContext, useEffect, useMemo, useState } from "react";

export const LanguageContext = createContext();

const translations = {
  en: {
    appTitle: "Personal Finance",
    login: "Login",
    register: "Register",
    logout: "Logout",
    language: "Language",
    email: "Email",
    password: "Password",
    name: "Name",
    dashboard: "Dashboard",
    transactions: "Transactions",
    reports: "Reports",
    settings: "Settings",
    addTransaction: "Add Transaction",
    attachedFiles: "Attached files",
    type: "Type",
    category: "Category",
    amount: "Amount",
    date: "Date",
    actions: "Actions",
    files: "Files",
    report: "Report",
    trip: "Trip",
    save: "Save",
    cancel: "Cancel",
    transactionsTitle: "Transactions",
    addNewTransaction: "Add New Transaction",
    addReceipt: "+ Add receipt",
    createReport: "+ Create report",
    createTrip: "+ Create trip",
    financialReport: "Financial Report",
    monthlyProfitStatistics: "Monthly Profit Statistics",
    revenueVsCost: "Revenue vs Cost",
    totalIncome: "Total Income",
    totalExpense: "Total Expense",
    netBalance: "Net Balance",
    noData: "No Data Available",
    settingsTitle: "Settings",
    profile: "Profile",
    security: "Security",
    notifications: "Notifications",
    emailAlerts: "Email Alerts",
    pushNotifications: "Push Notifications",
    appearance: "Appearance",
    darkMode: "Dark Mode",
    saveChanges: "Save Changes",
    changesSaved: "Changes saved successfully!",
    edit: "Edit",
    delete: "Delete",
    monthlyReport: "Monthly Report",
    month: "Month",
    total: "Total",
  },
  ta: {
    appTitle: "தனிநபர் நிதி",
    login: "உள்நுழை",
    register: "பதிவு",
    logout: "வெளியேறு",
    language: "மொழி",
    email: "மின்னஞ்சல்",
    password: "கடவுச்சொல்",
    name: "பெயர்",
    dashboard: "டாஷ்போர்டு",
    transactions: "பரிவர்த்தனைகள்",
    reports: "அறிக்கைகள்",
    settings: "அமைப்புகள்",
    addTransaction: "பரிவர்த்தனை சேர்க்க",
    attachedFiles: "இணைக்கப்பட்ட கோப்புகள்",
    type: "வகை",
    category: "வகை பெயர்",
    amount: "தொகை",
    date: "தேதி",
    actions: "செயல்கள்",
    files: "கோப்புகள்",
    report: "அறிக்கை",
    trip: "பயணம்",
    save: "சேமிக்க",
    cancel: "ரத்துசெய்",
    transactionsTitle: "பரிவர்த்தனைகள்",
    addNewTransaction: "புதிய பரிவர்த்தனை",
    addReceipt: "+ ரசீது சேர்க்க",
    createReport: "+ அறிக்கை உருவாக்க",
    createTrip: "+ பயணம் உருவாக்க",
    financialReport: "நிதி அறிக்கை",
    monthlyProfitStatistics: "மாதாந்திர புள்ளிவிவரம்",
    revenueVsCost: "வருமானம் vs செலவு",
    totalIncome: "மொத்த வருமானம்",
    totalExpense: "மொத்த செலவு",
    netBalance: "நிகர இருப்பு",
    noData: "தரவு இல்லை",
    settingsTitle: "அமைப்புகள்",
    profile: "சுயவிவரம்",
    security: "பாதுகாப்பு",
    notifications: "அறிவிப்புகள்",
    emailAlerts: "மின்னஞ்சல் அறிவிப்புகள்",
    pushNotifications: "புஷ் அறிவிப்புகள்",
    appearance: "தோற்றம்",
    darkMode: "கரும்படை",
    saveChanges: "மாற்றங்களை சேமிக்க",
    changesSaved: "மாற்றங்கள் வெற்றிகரமாக சேமிக்கப்பட்டன!",
    edit: "திருத்த",
    delete: "அழிக்க",
    monthlyReport: "மாதாந்திர அறிக்கை",
    month: "மாதம்",
    total: "மொத்தம்",
  },
  hi: {
    appTitle: "व्यक्तिगत वित्त",
    login: "लॉगिन",
    register: "पंजीकरण",
    logout: "लॉगआउट",
    language: "भाषा",
    email: "ईमेल",
    password: "पासवर्ड",
    name: "नाम",
    dashboard: "डैशबोर्ड",
    transactions: "लेनदेन",
    reports: "रिपोर्ट",
    settings: "सेटिंग्स",
    addTransaction: "लेनदेन जोड़ें",
    attachedFiles: "संलग्न फाइलें",
    type: "प्रकार",
    category: "श्रेणी",
    amount: "राशि",
    date: "तारीख",
    actions: "क्रियाएँ",
    files: "फाइलें",
    report: "रिपोर्ट",
    trip: "यात्रा",
    save: "सहेजें",
    cancel: "रद्द करें",
    transactionsTitle: "लेनदेन",
    addNewTransaction: "नया लेनदेन",
    addReceipt: "+ रसीद जोड़ें",
    createReport: "+ रिपोर्ट बनाएँ",
    createTrip: "+ यात्रा बनाएँ",
    financialReport: "वित्तीय रिपोर्ट",
    monthlyProfitStatistics: "मासिक सांख्यिकी",
    revenueVsCost: "राजस्व बनाम लागत",
    totalIncome: "कुल आय",
    totalExpense: "कुल खर्च",
    netBalance: "शुद्ध शेष",
    noData: "कोई डेटा उपलब्ध नहीं",
    settingsTitle: "सेटिंग्स",
    profile: "प्रोफ़ाइल",
    security: "सुरक्षा",
    notifications: "सूचनाएँ",
    emailAlerts: "ईमेल अलर्ट",
    pushNotifications: "पुश सूचनाएँ",
    appearance: "दिखावट",
    darkMode: "डार्क मोड",
    saveChanges: "परिवर्तन सहेजें",
    changesSaved: "परिवर्तन सफलतापूर्वक सहेजे गए!",
    edit: "संपादित करें",
    delete: "हटाएँ",
    monthlyReport: "मासिक रिपोर्ट",
    month: "महीना",
    total: "कुल",
                  
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("lang") || "en");

  useEffect(() => {
    localStorage.setItem("lang", lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const t = useMemo(() => translations[lang], [lang]);

  const value = useMemo(() => ({ lang, setLang, t }), [lang, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}


